### ISSUE TITLE
Provisioners will not be run since container doesn't support SSH.

### ISSUE THREAD

**Issue by wkoertgen** [wkoertgen/train.docker.dataguard#1]
It seems vagrant refuses to execute the setup script now

```
hwk@Thinkpad4:~/git/train.docker.dataguard$ vagrant up
Bringing machine 'train.docker.dataguard' up with 'docker' provider...
==> train.docker.dataguard: Creating the container...
    train.docker.dataguard:   Name: oracle12c
    train.docker.dataguard:  Image: oraclelinux:7.1
    train.docker.dataguard:    Cmd: /bin/bash -ci ./setup.sh
    train.docker.dataguard: Volume: /home/hwk/git/train.docker.dataguard/install:/tmp
    train.docker.dataguard:   Port: 1521:1521
    train.docker.dataguard:  
    train.docker.dataguard: Container created: 451e8c01cfead265
==> train.docker.dataguard: Starting container...
==> train.docker.dataguard: Provisioners will not be run since container doesn't support SSH.
```

**Comment by mkoertgen** [comment]
Does setting `has_ssh = true` in vagrants docker config help?
- https://github.com/mitchellh/vagrant/issues/3923#issuecomment-44457374
- https://docs.vagrantup.com/v2/docker/configuration.html

I will look into this...

**Comment by wkoertgen** [comment]
Adding

```
config.vm.provider "docker" do |d|
    d.has_ssh = true*
end
```

helped. But i get a connection timeout (no ssh key exchanged).

**Comment by mkoertgen** [comment]
This can be handled like 

https://github.com/mitchellh/vagrant/issues/3799

**Comment by wowcigar** [comment]
os windows:
open vagrantfile under folder of scrapybook by txt
add " d.has_ssh =true " above each line such as "d.force_host_vm = force_host_vm"
save
try vagrant up --no-parallel
should be successful
login and passwd as vagrant under docker container

**Comment by alxfed** [comment]
ty @wowcigar!
